[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable all post-processing to ensure our built files are served as-is
[build.processing]
  skip_processing = true